= Python
Wubbo Lameijer, 20240514
v1.0.0

== Inleiding: waarom Python?
Python is oftewel de grootste of op 1 na grootste programmeertaal ter wereld, afhankelijk van of je Tiobe (https://www.tiobe.com/tiobe-index/) of Redmonk (https://redmonk.com/sogrady/2024/03/08/language-rankings-1-24/) gelooft.

Populair betekent natuurlijk niet automatisch goed, maar Python heeft zeker een zeer grote niche: het is een taal ontworpen voor (en, zeker oorspronkelijk, door) mensen die geen professionele developer zijn (wat de grote meerderheid van de mensheid is!). De ontwikkelaar van Python, Guido van Rossum, was een wiskundige en academicus werkend aan het CWI (Centrum voor Wiskunde en Informatica in Amsterdam), en in tegenstelling tot andere talen ontwikkeld door wiskundigen (zoals Haskell) streefde hij ernaar een taal te maken die eenvoudig, leesbaar, en voor iedereen toegankelijk was; in feite een opvolger voor BASIC, maar een die gebruik kon maken van de rekenkracht van moderne computers, en niet de onfortuinlijke connotatie had dat het een taal voor "beginners" was (BASIC = Beginner's All-purpose Symbolic Instruction Code). Python werd redelijk snel populair in de academische wereld (alternatieven in die tijd waren C, C++, Scheme en Haskell, die studenten meer hoofdpijn bezorgden), maar ook systeembeheerders begonnen de taal over te nemen, als alternatief voor het moeilijk onderhoudbare Perl.

Dat wil niet zeggen dat Python (dat in 1991 uitkwam) gelijk een hit was. Je kon er algoritmes in schrijven en tekstfiles lezen en schrijven, maar het had weinig capaciteiten buiten wat je nodig had voor een universitaire cursus in algoritmen (met Python kon je geen databases lezen en schrijven, afbeeldingen inlezen en bewerken, of programma's maken met een grafische user-interface...) Het kostte jaren voordat mensen 'in de industrie' serieus Python gingen gebruiken, het bekendste database-framework voor Python, Django, kwam pas in 2005 uit, 14 jaar na de release van Python zelf. Java, die wel ontworpen was door (en voor) professionele developers, lanceerde gelijk met capaciteiten voor databases, GUIs en internet. (al kan je van Rossum moeilijk verwijten dat hij geen internetcapaciteiten inbouwde, het internet was nog niet erg populair in 1991).

Nu zal ik niet zeggen dat de onstuimige groei van Python de afgelopen 10-20 jaar betekent dat je moet stoppen met Java en over moet schakelen op Python. Allereerst is er het strategische baanzoekaspect: omdat Python massaal wordt onderwezen aan studenten en geleerd wordt door beginners, heb je enorme concurrentie van 'perfecte werknemers' - jonge mannen en vrouwen van een jaar of 22 die een universitaire bul hebben gehaald en toevallig ook Python hebben geleerd. Bij talen als Java en C# is de concurrentie veel en veel kleiner. 

Ten tweede is Python mogelijk niet (alleen) een taal voor beginners, maar wel een taal waarbij de voornaamste niche is dat het gebruikt wordt door mensen die niet voltijds software ontwikkelen. Daar is de taal ook op gericht. Maar het gevolg is wel dat 'steigerbouw' die ontzettend nuttig is voor programma's die je in een groep bouwt over een periode van jaren vrijwel geheel ontbreekt wegens de 'belasting' van de extra tekst. Typen van parameters zijn niet verplicht, dus er zijn geen compilerwaarschuwingen als je een methode aanroept met verkeerde parametertypen (tegenwoordig kan je het wel instellen, maar daarvoor moet je extra moeite doen, in tegenstelling tot Java dat vindt dat je niet moet zeuren); een typefout zal Python ook zelden opvallen, omdat je dynamisch leden kan declareren op klassen, en een variabele die eerst een string is een integer-waarde kan geven. Python heeft geen private variabelen en constanten, anders dan door 'naamsconventies' - die door verstrooide of haastige programmeurs makkelijk gehackt kunnen worden. Het Python-motto "We're all consenting adults here" is een stuk minder handig in een industriele omgeving, waar anders dan in de academische wereld de hete adem van managers en de kosten van de hypotheek het vaak wel heel verleidelijk te maken 'short term shortcuts' te nemen die je op langere termijn gaan opbreken. Buiten de beginset is de taal relatief lastig te onthouden omdat je zelden weet of iets een methode is (zoals "hello".upper()) of een functie (len(a)), wat autocomplete lastig maakt. Er zijn ook problemen met significant whitespace, bibliotheekbeheer, snelheid, de groottebeperking van lambda's, en multithreading die tot nog toe niet zijn opgelost omdat ongeveer elke oplossing bergen Python-code zal breken. Python is nog steeds een taal van 'trial en error', die het motto "Fail fast, fail cheap" (oftewel: een compiler-error is beter dan een crash bij een klant) niet gebruikt. En naarmate een programma groeit, wordt de tijd je je moet investeren het op een 'trial-and-error' manier werkend te krijgen exponentieel groter. En als iemand die ook in Python heeft moeten programmeren voor opdrachtgevers heb ik wel enig begrip van het citaat van ene Jack Jansen, scientific programmer en software engineer: "Python is a truly wonderful language. When somebody comes up with a good idea, it takes about 1 minute and five lines to program something that almost does what you want. Then it takes only an hour to extend the script to 300 lines, after which it still does almost what you want."

Toch zijn er zeker serieuze redenen om Python te leren. Allereerst behoort Python tot de top-3-talen met nuttige bibliotheken. Java heeft ontzettend veel bibliotheken voor de traditionele enterprise (dataverwerking en databases, maar ook bv internet), JavaScript heeft ook enorm veel bibliotheken (vooral dus voor frontend), Python heeft enorm veel bibliotheken voor AI en machine learning en dataanalyse (een bedrijf waar ik ooit solliciteerde analyseerde Chinese bedrijven en hun connecties, Python was daar een logische keus voor), en een bijna oneindige hoeveelheid voor tekst parsers en kleine tools. Als je Python beheerst breid je je toolkit flink uit!

Ten tweede is Python een beetje de standaard 'glue-taal': niet iets om de meeste apps in te schrijven, maar handig voor scriptjes die A naar B omzetten zonder dat je een programma lokaal moet compileren. Het kan goed samenwerken met andere pipelines, dus de kans is redelijk groot dat je af en toe wat in Python zal schrijven als een Java-applicatietje bouwen voor iets gewoon overkill is.

En ten derde zijn er relatief veel werkgevers die voor Python kiezen, sommigen hebben mogelijk gehoord dat Python zo compact en makkelijk te gebruiken is, anderen denken dat ze makkelijk Python-programmeurs zullen kunnen werven omdat ongeveer iedereen Python kan. Één van onze deelnemers die bij een bank solliciteerde vertelde dat de manager die hem interviewde van geen enkele programmeertaal die hij noemde enthousiast leek te worden, behalve voor Python. Nu kan ik als developer wel zelf een mening hebben over hoe geschikt Python is voor projecten die niet gebruik maken van Python's niche in libraries (dataanalyse en AI e.d.), zeker ten opzichte van modernere talen die wel vanaf de grond zijn ontworpen voor professionele softwareontwikkeling - maar zelfs als het in Python 2 of 3 keer zo lang duurt om dezelfde features te implementeren als in Java: als een manager of team voor Python kiest en daar het geld en tijd voor overheeft, en het onderwerp en team is verder leuk... Python zal zelden zo handicappend zijn dat het een project de nek omdraait, en als Python de kansen op een baan vergroot - waarom het dan niet leren? Zeker omdat het in mijn ervaring (via bijvoorbeeld https://docs.python.org/3/tutorial/index.html) slechts een middagje kost voor een ervaren developer om Python te leren, dus de tijdsinvestering is miniem (uiteraard kost het meer tijd om frameworks als Django te leren, maar daar is voldoende voorbeeldcode voor op internet om in een paar dagen een eenvoudig demoproject in elkaar te kunnen zetten als dat je nuttig lijkt voor een sollicitatie).

== De Uitdaging
Mogelijk dat iemand het leuk vindt met een of meerdere van de Python-biblioteken voor dataverwerking (NumPy, Pandas) of machine learning/AI (PyTorch, Keras, Hugging Face Transformers, TensorFlow) aan de slag te gaan. Maar ik heb toevallig geen grote datasets, en we zijn natuurlijk een programmeeropleiding, geen opleiding tot data scientist, dus als je AI/ML geinteresseerd bent, doe het als hobbyproject (of laat me een uitgevoerd idee weten als bonusopdracht), als developer zal ik een wat saaiere (en mogelijk wel veeleisendere, want je moet echt iets afleveren inplaats van wat te spelen met paremetersettings om te kijken of er een 'beter' model uit kan komen)

De opdracht is: maak een eenvoudige fullstack-app in Django. Maar dan NIET met een JavaScript-frontend, maar op de template-manier, dan leer je dat ook.

Een receptenapp, supermarkt-app, vrienden-bijhoud-app: het hoeft allemaal niet fancy (sowieso is dingen fancy maken niet makkelijk met template-files), kies iets dat eenvoudig is, gewoon data (hoeven geen plaatjes te zijn) tonen en aanmaken in frontend en op kunnen slaan in backend.


== Tijd/moeilijkheid (praktijk)
Geschat: ongeveer 1 dag (inclusief Python leren)

== Als je meer wilt weten 
. https://docs.python.org/3/tutorial/index.html
. https://docs.djangoproject.com/en/5.0/ (over Django)
. "Fluent Python" vond ik zelf een erg goed en diep boek, als je echt een Python-meester zou willen worden. Er is tegenwoordig ook een tweede editie van, ook soms als pdf op internet...

